<?xml version="1.0"?>

<robot xmlns:xacro="http://ros.org/wiki/xacro">
  
  <!-- Includes -->
  <xacro:include filename="palletron_base.gazebo.xacro"/>
  <xacro:include filename="../wheels/caster_wheel.urdf.xacro"/>
  <xacro:include filename="../wheels/drive_wheel.urdf.xacro"/>

  <!-- TODO: Update according to real base properties -->
  
  <!-- Base properties -->
  <xacro:property name="base_mass" value="25.0"/>
  <xacro:property name="base_width" value="0.7"/>
  <xacro:property name="base_depth" value="0.7"/>
  <xacro:property name="base_height" value="0.7"/>

  <!-- Drive wheel properties -->
  <xacro:property name="wheel_separation" value="0.33"/>
  <xacro:property name="wheel_width" value="0.05"/>
  <xacro:property name="wheel_radius" value="0.13"/>
  <xacro:property name="wheel_mass" value="4.0"/>
  <xacro:property name="wheel_z_offset" value="-0.275"/>
  <xacro:property name="wheel_max_acceleration" value="1.0"/>
  <xacro:property name="wheel_max_torque" value="6.0"/>

  <!-- Caster wheel properties -->
  <xacro:property name="caster_radius" value="0.045"/>
  <xacro:property name="caster_mass" value="4.0"/>
  <xacro:property name="caster_x_offset" value="0.25"/>
  <xacro:property name="caster_y_offset" value="0.25"/>
  <xacro:property name="caster_ground_offset" value="0.005"/>

  <!-- Base -->
  <xacro:macro name="palletron_base">
    <link name="base_footprint"/>

    <joint name="base_joint" type="fixed">
      <parent link="base_footprint"/>
      <child link="base_link" />
      <origin xyz="0 0 ${wheel_radius - wheel_z_offset}" rpy="0 0 0"/>
    </joint>

    <link name="base_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${base_width} ${base_height} ${base_depth}"/>
        </geometry>
        <material name="blue"/>
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${base_width} ${base_height} ${base_depth}"/>
        </geometry>
        <material name="orange"/>
      </collision>

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${base_mass}"/>
        <xacro:box_inertia m="${base_mass}" h="${base_height}" d="${base_depth}" w="${base_width}"/>
      </inertial>
    </link>

    <!-- Gazebo extentions -->
    <xacro:palletron_base_gazebo/>
    
    <!-- Drive wheels -->
    <xacro:drive_wheel name="wheel_right"
      radius="${wheel_radius}"
      mass="${wheel_mass}"
      z_offset="${wheel_z_offset}"
      width="${wheel_width}"
      separation="${wheel_separation}"
      reflect="1.0"
      parent="base_link"/>

    <xacro:drive_wheel name="wheel_left"
      radius="${wheel_radius}"
      mass="${wheel_mass}"
      z_offset="${wheel_z_offset}"
      width="${wheel_width}"
      separation="${wheel_separation}"
      reflect="-1.0"
      parent="base_link"/>

    <!-- Caster wheels -->
    <xacro:caster_wheel name="caster_front_right"
      radius="${caster_radius}"
      mass="${caster_mass}"
      x_offset="-${caster_x_offset}"
      y_offset="${caster_y_offset}"
      z_offset="${wheel_z_offset + caster_ground_offset - (wheel_radius - caster_radius)}"
      parent="base_link"/>

    <xacro:caster_wheel name="caster_front_left"
      radius="${caster_radius}"
      mass="${caster_mass}"
      x_offset="${caster_x_offset}"
      y_offset="${caster_y_offset}"
      z_offset="${wheel_z_offset + caster_ground_offset - (wheel_radius - caster_radius)}"
      parent="base_link"/>

    <xacro:caster_wheel name="caster_rear_left"
      radius="${caster_radius}"
      mass="${caster_mass}"
      x_offset="${caster_x_offset}"
      y_offset="-${caster_y_offset}"
      z_offset="${wheel_z_offset + caster_ground_offset - (wheel_radius - caster_radius)}"
      parent="base_link"/>

    <xacro:caster_wheel name="caster_rear_right"
      radius="${caster_radius}"
      mass="${caster_mass}"
      x_offset="-${caster_x_offset}"
      y_offset="-${caster_y_offset}"
      z_offset="${wheel_z_offset + caster_ground_offset - (wheel_radius - caster_radius)}"
      parent="base_link"/>
  </xacro:macro>
</robot>