<?xml version="1.0"?>

<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:macro name="palletron_base_gazebo">
    <!-- Material -->
    <gazebo reference="base_link">
      <material>Gazebo/Blue</material>
    </gazebo>

    <gazebo reference="base_footprint">
      <!-- Contact model -->
      <kp>100000000.0</kp>
      <kd>10.0</kd>
      <mu1>0.1</mu1>
      <mu2>0.1</mu2>
      <fdir1>1 0 0</fdir1>
      <maxVel>10.0</maxVel>
      <minDepth>0.0005</minDepth>
      <laserRetro>0</laserRetro>
    </gazebo>

    <gazebo>
      <!-- Differencial driver plugin -->
      <plugin name="gazebo_ros_diff_drive_controller" filename="libgazebo_ros_diff_drive.so">
        <ros>
          <remapping>/tf:=tf</remapping>
        </ros>
        <odometry_topic>odom</odometry_topic>
        <odometry_frame>odom</odometry_frame>
        <update_rate>30</update_rate>
        <left_joint>wheel_left_joint</left_joint>
        <right_joint>wheel_right_joint</right_joint>
        <wheel_separation>${wheel_separation}</wheel_separation>
        <wheel_diameter>${wheel_radius * 2}</wheel_diameter>
        <max_wheel_torque>${wheel_max_torque}</max_wheel_torque>
        <max_wheel_acceleration>${wheel_max_acceleration}</max_wheel_acceleration>
        <command_topic>cmd_vel</command_topic>
        <publish_odom>true</publish_odom>
        <robot_base_frame>base_footprint</robot_base_frame>
      </plugin>
    </gazebo>
  </xacro:macro>  
</robot>