<?xml version="1.0"?>

<robot name="palletron" xmlns:xacro="http://ros.org/wiki/xacro">
  <!-- Includes -->
  <xacro:include filename="common_properties.urdf.xacro"/>
  <xacro:include filename="inertias.urdf.xacro"/>
  
  <xacro:include filename="chassis/chassis_without_mesh.urdf.xacro"/>
  
  <xacro:include filename="plugins/differential_drive_plugin.gazebo.xacro"/>
  <xacro:include filename="plugins/p3d_plugin.gazebo.xacro"/>
  
  <xacro:include filename="sensors/hokuyo.urdf.xacro"/>
  <xacro:include filename="sensors/imu.urdf.xacro"/>

  <xacro:include filename="wheels/drive_wheel.urdf.xacro"/>
  <xacro:include filename="wheels/dummy_caster_wheel.urdf.xacro"/>
  
  <!-- Load arguments -->
  <xacro:property name="namespace" value="$(arg namespace)"/>

  <!-- Load optional properties file -->
  <xacro:property name="optional_properties" value="$(arg optional_properties)"/>
  <xacro:property name="optionals" value="${xacro.load_yaml(optional_properties)}"/>
  
  <!-- Chassis parameters -->
  <xacro:property name="mass" value="10.0"/>
  <xacro:property name="chassis_width" value="0.6"/>
  <xacro:property name="chassis_length" value="0.7"/>
  <xacro:property name="chassis_height" value="0.7"/>
  <xacro:property name="chassis_offset_x" value="-0.275"/>
  <xacro:property name="chassis_offset_z" value="0.45"/>
   
  <!-- Drive wheels parameters -->
  <xacro:property name="drive_wheel_mass" value="1.0"/>
  <xacro:property name="drive_wheel_radius" value="0.045"/>
  <xacro:property name="drive_wheel_width" value="0.03"/>
  <xacro:property name="drive_wheel_separation" value="0.45"/>
  <xacro:property name="drive_wheel_max_acceleration" value="1.0"/>
  <xacro:property name="drive_wheel_max_torque" value="10.0"/>
   
  <xacro:property name="right_drive_wheel_prefix" value="right_wheel"/>
  <xacro:property name="left_drive_wheel_prefix" value="left_wheel"/>
  
  <!-- Dummy caster wheels parameters -->
  <xacro:property name="dummy_caster_wheel_radius" value="0.045"/>
  <xacro:property name="dummy_caster_wheel_offset_x" value="-1.425"/>
  <xacro:property name="dummy_caster_wheel_offset_y" value="0.0"/>
  <xacro:property name="dummy_caster_wheel_offset_ground" value="0.00125"/>

  <xacro:property name="dummy_caster_wheel_prefix" value="front_caster_wheel"/>
  
  <!-- Chassis without mesh -->
  <xacro:chassis_without_mesh_macro robot_namespace="${namespace}"
    mass="${mass}"
    chassis_width="${chassis_width}"
    chassis_length="${chassis_length}"
    chassis_height="${chassis_height}">
    <!-- Base footprint origin (from base link) -->
    <origin xyz="0 0 ${-drive_wheel_radius}" rpy="0 0 0"/>
    <!-- Chassis origin (from base link) -->
    <origin xyz="${chassis_offset_x} 0 ${chassis_offset_z}" rpy="0 0 0"/>
  </xacro:chassis_without_mesh_macro>
  
  <!-- Differential drive plugin -->
  <xacro:differential_drive_plugin_macro robot_namespace="${namespace}"
    right_wheel_prefix="${right_drive_wheel_prefix}"
    left_wheel_prefix="${left_drive_wheel_prefix}"
    wheel_separation="${drive_wheel_separation}"
    wheel_diameter="${drive_wheel_radius*2}"
    wheel_max_torque="${drive_wheel_max_torque}"
    wheel_max_acceleration="${drive_wheel_max_acceleration}">
  </xacro:differential_drive_plugin_macro>

  <!-- Right drive wheel -->
  <xacro:drive_wheel_macro robot_namespace="${namespace}"
    parent="base_link"
    prefix="${right_drive_wheel_prefix}"
    mass="${drive_wheel_mass}"
    radius="${drive_wheel_radius}"
    length="${drive_wheel_width}"
    xyz="0 ${-drive_wheel_separation/2} 0">
  </xacro:drive_wheel_macro>

  <!-- Left drive wheel -->
  <xacro:drive_wheel_macro robot_namespace="${namespace}"
    parent="base_link"
    prefix="${left_drive_wheel_prefix}"
    mass="${drive_wheel_mass}"
    radius="${drive_wheel_radius}"
    length="${drive_wheel_width}"
    xyz="0 ${drive_wheel_separation/2} 0"> 
  </xacro:drive_wheel_macro>
  
  <!-- Dummy caster wheel -->
  <xacro:dummy_caster_wheel_macro robot_namespace="${namespace}"
    parent="base_link"
    prefix="${dummy_caster_wheel_prefix}"
    radius="${dummy_caster_wheel_radius}"
    xyz="${dummy_caster_wheel_offset_x} ${dummy_caster_wheel_offset_y} ${dummy_caster_wheel_offset_ground - (drive_wheel_radius - dummy_caster_wheel_radius)}">
  </xacro:dummy_caster_wheel_macro>

  <!-- Right laser ranger scanner -->
  <xacro:hokuyo_macro robot_namespace="${namespace}"
    parent="base_link"
    prefix="right">
    <origin xyz="${chassis_width/2 + (chassis_offset_x + 0.025)} -${chassis_length/2 + 0.025} 0.10" rpy="${rad180} 0 ${-rad45}"/>
  </xacro:hokuyo_macro>

  <!-- Left laser ranger scanner -->
  <xacro:hokuyo_macro robot_namespace="${namespace}"
    parent="base_link"
    prefix="left">
    <origin xyz="${chassis_offset_x - (chassis_width/2 + 0.025)} ${chassis_length/2 + 0.025} 0.10" rpy="${rad180} 0 ${rad135}"/>
  </xacro:hokuyo_macro>

  <!-- IMU 0 -->
  <xacro:imu_macro robot_namespace="${namespace}"
    parent="base_link"
    suffix="0">
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </xacro:imu_macro>

  <!-- IMU 1 -->
  <xacro:imu_macro robot_namespace="${namespace}"
    parent="base_link"
    suffix="1">
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </xacro:imu_macro>

  <!-- Ground truth (P3D) plugin -->
  <xacro:if value="${optionals['enable_ground_truth']}">
    <xacro:p3d_plugin_macro robot_namespace="${namespace}"
      parent="base_link"
      update_rate="100"
      topic_name="odometry/ground_truth"
      mass="0.00001"
      body_name="base_link"
      frame_name="world"
      noise="0"
      xyz_offset="0 0 0"
      rpy_offset="0 0 0">
      <inertia ixx="0.00001" ixy="0" ixz="0" iyy="0.00001" iyz="0" izz="0.00001"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:p3d_plugin_macro>
  </xacro:if>
</robot>